name: do_an_ui
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0

  regexed_validator: ^1.0.4

  auto_route: ^0.6.9

  webview_flutter: ^1.0.7

  screenshot: ^0.2.0

  toast: ^0.1.5

  bubble: ^1.1.9+1

  rxdart: ^0.25.0
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.9+3
  build_runner:
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/bg/
    - icons/

  fonts:
    - family: Aquire
      fonts:
      - asset: fonts/Aquire.ttf
      - asset: fonts/Aquire-Bold.ttf
      - asset: fonts/Aquire-Light.ttf

    - family: Roboto
      fonts:
      - asset: fonts/Roboto.ttf
      - asset: fonts/Roboto-Bold.ttf

    - family:  MyFont
      fonts:
      - asset: fonts/MyFont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
